### ISSUE TITLE
Bugs when opening the links in Gmail

### ISSUE THREAD

**Issue by leevy** [mozilla/multi-account-containers#1600]
- Multi-Account Containers Version: 6.1.1
- Operating System + Version: Mac OS Mojave 10.14.6
- Firefox Version: 70.0.1
- Other installed Add-ons + Version + Enabled/Disabled-Status:

### Actual behavior
When I try to open the links in Gmail, this add-on would ask me to chose which container I want to open it, but after I choose one specific container, the redirect link would be damaged and missing some parameters, so I won't go to the right page.

### Expected behavior
It should be the same link to open the right page.

### Steps to reproduce
1. Open any links in Gmail
2. This add-on asks for which container I want to open in
3. I choose one container
4. It opened the link in the designated container, but the link would be missing some part and end up with the wrong page

### Notes
Because Gmail is open any links with Google redirection, maybe that's the reason causing this problem

**Comment by mstojanovic** [comment]
i think that is something to do with how google treats links. when you open a link from youtube, even if it is something in a different container it will rederect to a google/youtube container.

**Comment by kendallcorner** [comment]
This addon does not ask you which container you would like to open a link in unless you're talking about the "Open this site in your assigned container?" page. If that's the issue and the link is not opening, try it with 6.2.0 which was released Wednesday, because we fixed an encoding/decoding issue in that release. If it's still not working, we may need an example of a link that creates this problem, because this is not reproducible for me.

**Comment by mstojanovic** [comment]
just tested it, works fairly well now but i still dont have a way out of the container.
e.g. here https://www.youtube.com/watch?v=wdKGtapi7WE we have links in comments, opening some links that are assigned to (different) containers works (e.g. amazon, facebook). but right clicking a link that isnt assigned to a container and choosing to open without containers ( http://pew.link/BiometricSafes) opens in a google container. more, since i have colors assigned to containers (google/youtube red, amazon purple, fb white) all links first start as a google container color then change to one that is assigned to the domain. 
![image](https://user-images.githubusercontent.com/3449343/74488497-aeb5e680-4ec2-11ea-83d2-8c31bb641b65.png)

technically, i could close the bug as solved, but there is some more issues imho

**Comment by kendallcorner** [comment]
Ah, I see the issue. Yeah, that is pretty unavoidable right now.  I didn't think about it this way at first, but when you click a link in gmail, it actually sends you to a google address in a new tab first, which redirects you to the correct link. So if you have google assigned to a container, this will always switch to a google container first and then to whatever container that site is assigned to. If the site is not assigned, it would just get stuck in the google container. Not ideal, but you can right click on the tab and 'reopen in ... ' another container.

We are working on pulling in a PR that can enact 'site isolation' that will automatically switch out of a container (e.g. a gmail container) once the page leaves that site. That would help with this.

I also wonder if a redirect remover addon would help with this issue as well.

**Comment by mstojanovic** [comment]
imho, after this i think this can be closed. the main issue i had now works more or less as it should. ill see for the redirect plugin usage

**Comment by dannycolin** [comment]
> We are working on pulling in a PR that can enact 'site isolation' that will automatically switch out of a container (e.g. a gmail container) once the page leaves that site. That would help with this.

I'm guessing that this is the "Limit to designated sites" option we have in the recent version right?

I'm closing this issue assuming that's the case but feel free to comment if it isn't and I'll reopen it.
