### ISSUE TITLE
7.0.X UX/UI Feedback 

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/multi-account-containers#1784]
We launched a new version of Multi-account Containers today. Please feel free to leave feedback on this issue. If you find a bug related to the new release, please file a separate issue. Thanks!

**Comment by redoPop** [comment]
My preferred way to open a new container is with `control`+`.` then use up/down arrows to select a container and press enter. The new UI adds some friction:

* Up/down arrows are no longer supported, so I had to switch to tab/shift+tab
* I have to press tab six times to cycle through the top menu before the first container is highlighted for selection
* Pressing enter on a container now opens a submenu in which I have to press tab twice again, then enter again, to open it

I'm sure it's a nice addition for some, but I'm unlikely to use the numeric shortcuts – I'm a TKL keyboard user so my touch-typing skills are iffy for the number keys 😅

**Comment by kuzi-moto** [comment]
> My preferred way to open a new container is with control+. then use up/down arrows to select a container and press enter. The new UI adds some friction:

I second @redoPop. Just updated and immediately realized that up/down arrows don't work which would be a huge inconvenience as I'm using that many times a day.

On a positive note, I noticed the option to open a specific bookmark in a container, which is a huge plus.

**Comment by maxxcrawford** [comment]
@redoPop Good call out. I [filed a bug](https://github.com/mozilla/multi-account-containers/issues/1785) for the arrow keys regression. Thanks!

**Comment by charles-m-knox** [comment]
Thank you guys for updating the multi-account containers extension, it's been a long time!

I have some direct feedback about the newest change: The "Always open in X container" option was very important. Being able to quickly see which container a page was associated with was very helpful. Now I have _no_ idea what sites are associated with a container, from what I can tell. I consider this a significant regression.

One huge improvement that needs to be made to the multi-account containers UI: I use a container for each domain, sometimes multiple for the same domain. My list of containers is quite large. It would be extremely helpful to add a filter/search box to the multi-account containers dropdown box. It is quite difficult to scroll through a long list of containers, hoping I find the right one. 

In fact, as a general rule, I should _never_ be required to scroll through a list of containers if it's longer than, say, 10 containers. I should be able to do a quick filter on the containers that I want. Any time I'm presented with a list of all the containers, I should have option to filter quickly by typing something in.

Additionally, since the list of containers are sorted chronological by creation date, the long list of containers is even more painful to sift through. So if a quick filter text box is not something that can easily be implemented, at least add the ability to quickly sort the list of containers alphabetically with a click of a button. This should be super easy to accomplish.

**Comment by umquat** [comment]
I have a suggestion in #1783. When you click on a container name, a new tab should open in that container (as it used to be before 7.0)

As @charles-m-knox  mentions, scrolling trough a long list can be burdensome; maybe filter on keystroke?

Container list could also be sortable with some kind of handle or maybe by usage (more frequently used at the top perhaps?)

Lastly, thanks a bunch for this extension!

**Comment by hr-curtissimo** [comment]
What @charles-m-knox writes:

> One huge improvement that needs to be made to the multi-account containers UI: I use a container for each domain, sometimes multiple for the same domain. My list of containers is quite large. It would be extremely helpful to add a filter/search box to the multi-account containers dropdown box. It is quite difficult to scroll through a long list of containers, hoping I find the right one.

That is so me, too. I have _a lot_ of containers. It'd be nice if I could just do `Control+N`, start typing the container I want, the list filters or smart-match selects or whatever, I hit Enter to open a tab in that container.

**Comment by extr3metech** [comment]
1. The keyboard navigation is not working with the new update. This is a huge productivity miss.

- Before the release I could do the following:
press CTRL + ., 
navigate using the arrow keys to the profile and then hit ENTER and I have a webpage open in that container. 

-With the current design, there is an too many keypresses to use to open a webpage in a container. Here what the new update did:
CTRL + .  => Opens the main menu.
Then ALT/TAB (or arrow keys when it gets fixed) to scroll to the selected container.
Then hit Enter, to go inside the container's menu.
Then scroll down again to select the option "Open new Tab in this container".

enter a nested menu in my opinion everytime is a huge productivity miss for a keyboard user. 

It would be nice to have an option to switch back the behavior to the default via a config option while keeping the new UI look. If a user needs to go to the nested menu, then a additional shortcut such as SHIFT and something else, will take inside the nested menu would be an added bonus.

**Comment by extr3metech** [comment]
-It would be nice to document somwhere visible within the plugin settings itself regarding the numberpad shortcuts.

**Comment by morachimo** [comment]
Congrats on the release! I'm a huge fan on the extension and I've been a great advocate of it for years.

I fully agree with @umquat (see #1783). I don't know how anyone else was using the extension but the new UI has added an extra step to my daily workflow. Expected behavior should be: 1. Clic on Menu Bar Button, 2. Choose container, 3. New window opens in that container. 

Sure, those extra 4 settings seem useful But why not putting those top four (4) settings on an overflow menu or only available once you're already into that container? I can expand on the idea (even graphically) if interested.

**Comment by vtuu** [comment]
#1786

**Comment by smerrill** [comment]
Chiming in to ask to please restore arrow key functionality. My workflow is hit Control-. and then use the up and down arrows to select the container in question.

Thanks for the great extension and browser!

**Comment by smerrill** [comment]
In the meantime is it possible to install an older release?

**Comment by Eduardo06sp** [comment]
Absolutely digging the beautifully designed, new options!
I would just love to know what Keyboard Shortcuts 1-10 mean (I figured out 1-9 is just the number row).

I'll try and dig into the revised code to see what that last one is lol

**Comment by Eduardo06sp** [comment]
Found the actual shortcuts in one of the commits:
**Ctrl + Shift + [1-9, or 0 on number row]**

To open your first 10 containers, which is configurable in the settings!!!

**Comment by extr3metech** [comment]
> That is so me, too. I have _a lot_ of containers. It'd be nice if I could just do `Control+N`, start typing the container I want, the list filters or smart-match selects or whatever, I hit Enter to open a tab in that container.

- I would love this as well. It would be perfect. (Similar to ranger file brower.)

**Comment by nikolaykhodov** [comment]
@smerrill 
 
> In the meantime is it possible to install an older release?

You may want to find older versions at https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/versions/
I have just downgraded to 6.2.5 with no pleasant experience: I had to uninstall the extension, install 6.2.5, disabled automatic updates for it:
 - it resetted to the default configuration
 - it was needed to restore custom containers (new/renamed default ones)
 - the downgrade's also wiped all cookies in non-default containers

**Comment by cptX** [comment]
The thing I realized immediately is that before the update I was clicking once on the prefered name of the container and a new tab on that container was openning right away. Now clicking on a name opens a second menu where I need to click again "Open new tab in this container" which is terribly unpractical. I don't understand why you changed that. It was so practical!! Please change it back!

**Comment by aafrasht** [comment]
I completely agree with @cptX.  @maxxcrawford You need to fix this!  I used to be able to open the container I want with one click, now it takes two.  It is insanely inconvenient.  And I don't really want to use keyword short-cuts as an alternatives.  Revert to one click please!

**Comment by cabello** [comment]
Let us all be mindful that this is free open source software provided by lovely volunteers and tune the tone.

I also noticed today that up/down arrows were not working anymore, excited to see this has already been filed as an issue and people are working on.

Thank you for this amazing extension, I use it on a daily basis and I feel I have more privacy with all the extra containers I use. 🙇

**Comment by angela-d** [comment]
Also parroting @cptX comment.
The extension constantly reminds me it's there by wasting my time with numerous clicks everytime I want to open a new tab.

Downgraded to the previous release and turned upgrades off on that extension.  Bad design, imo.  

Why was the UX change necessary?  It was a very seamless experience, prior.

**Comment by noph34r** [comment]
i prefer the "old' one when i can just click and open new empty tab
but now i have to click twice just to open one....

i have 10 container and those are waste of time, might as well using the old kind or have "open all container" in single click

**Comment by tomaspapi** [comment]
The update looks much cleaner, congrats. Two pieces of feedback:

- "Always open this site in this container", "Create a new container" and "Open a container" used to take a single click (after opening the add-on icon) by checking the box on the top, hitting the `+` icon on the bottom right and clicking on the name of a container, respectively. All of these require now an additional click. I'd love all the features and functionalities that made that possible back. Like, it takes the same amount of clicks to edit the name of a container, or change the colour, than it takes to open one — which is a foundational, very basic and everyday use of the extension.

- For people who have many containers (i.e. one per domain), this update is extremely inconvenient. Everything requires going through your entire container list — not only opening one (as it used to be already) but also now assigning this domain to the current container, since the checking box is gone. And they are not even ordered properly so finding the correct container is terrible. The ability to order alphabetically would be awesome and having a search box would be a plus too.

I'll use this opportunity to include some general features I'd love to see in the extension as well:

- Ability to include all subdomains of a domain in a container (i.e. `*.domain.com`)
- Ability to add domains without having to actually go to that site (like writing it in the "Manage Container" setting)
- Ability to export configuration and settings

This is one of my favourite extensions, thanks for all the work you do.

**Comment by eefi** [comment]
I noticed on macOS that the default mapping of the numbered shortcuts to Cmd+Shift+3, Cmd+Shift+4, etc. conflicts with the macOS shortcuts for taking screenshots. I've filed #1791 to track this.

**Comment by eefi** [comment]
An idea for those who want the old simple container opening flow from up/down arrows… Can either Multi-Account Containers or Firefox itself provide a keyboard shortcut to access the long-press-on-new-tab-button containers menu? I'm referring to the menu that was made more accessible in https://bugzilla.mozilla.org/show_bug.cgi?id=1606265.

If there's a keyboard shortcut to open that menu with the first container highlighted, then it can provide a place where up and down cycle through the list of containers, and Enter immediately opens a new tab with that container. (I explicitly suggest starting with the first container highlighted rather than the likely default implementation of having the "No Container" first element highlighted to start because anyone using a keyboard shortcut to access this menu would likely just use Ctrl+T/Cmd+T to open a new tab with no container.)

Then the new more complex UI in the Multi-Account Containers panel can remain for the more complex management tasks it seems designed for.

**Comment by eefi** [comment]
> I have some direct feedback about the newest change: The "Always open in X container" option was very important. Being able to quickly see which container a page was associated with was very helpful. Now I have _no_ idea what sites are associated with a container, from what I can tell. I consider this a significant regression.

@charles-m-knox I found where this is located… From the Multi-Account Containers panel, click on the Manage Containers bar on the bottom, then click your container, and finally there's a Manage SIte List… link toward the bottom of the panel.

**Comment by klaritan** [comment]
Not liking this new UI only because I have to click twice to open a new tab on a container. I know I can still click once but that requires secondary click on a smaller button.

**Comment by aibaraiduas** [comment]
I like the new UI, but the icon's color should probably be a lighter gray to match Firefox's default icons. I'm using the default Firefox theme in Ubuntu.

![Screenshot from 2020-07-12 14-18-08](https://user-images.githubusercontent.com/5825551/87253751-a3ec8700-c44b-11ea-9c37-8029e9777ab5.png)

**Comment by maxxcrawford** [comment]
@charles-m-knox Great idea. I filed an issue for that feature, as you described. #1796

**Comment by maxxcrawford** [comment]
@aibaraiduas Issue filed! Thanks!

**Comment by charles-m-knox** [comment]
> 
> 
> @charles-m-knox Great idea. I filed an issue for that feature, as you described. #1796

Thank you @maxxcrawford , you're doing a great job, thank you for putting the work in on this extension. It's really a game changer.

**Comment by maxxcrawford** [comment]
Thank you everyone who commented on this thread for the feedback! We're going to continue to watch this thread (and the other incoming issues) as we get our new patch/release ready. 🦊

**Comment by ca1f** [comment]
I like the new UI/UX so far, it would be helpful though if the small box opened via the `Ctrl + .` shortcut would also show the number associated with the given container so that I don't need to recall it from memory.

**Comment by mestuddtc** [comment]
I find the new UI horrible. I have my tabs set up, so the only action I ever take is to open a new tab. This has gone from click, move to large target directly beneath, click, to click, move over junk to much smaller, further away target which is harder to hit, click, reorient myself to find the open action, move back up to another small target, click. It takes three? times as long, which is quite aggravating for something I do possibly hundreds of times a day.

**Comment by ZingBlue** [comment]
The "Reopen This Site In" button, only shows up on the main page but not on any container's pages. I'll make a PR to fix this if that's good.

**Comment by glandium** [comment]
I'm not a fan of the increased number of clicks when opening a new tab.
The reduction in font size makes the menu have empty white space at the bottom when there aren't many containers (which is true with the default set of containers).
But more importantly, I don't agree that the menu should have a different font size than other menus in Firefox.
The "manage containers" menu item doesn't react like others. The cursor changes when hovering it but it's not highlighted in any way, which is inconsistent.
Something that was true before 7.0: "Reopen This Site in..." doesn't sound to me like it's going to open a new tab and leave the current one open. Especially when combined with the fact that it has the same icon as the "reload" button. I wish it were able to reopen in place, but AFAIK, Firefox doesn't support switching containers on an existing tab (and restoring the previous container when hitting back ; I wish it were able to, that would make this so much more slick IMHO).

**Comment by michft-v** [comment]
The submenu option doesn't work for me and is an additional step (degradation of UI experience). I use Multi container to primarily have multiple tabs (and thus cookies) from the same site open at the same time in different containers (AWS SAML). The submenu step to always open in a particulat container doesn't work with this workflow. I would like to have the link either sub-menu open to have a default action form the main menu. The arrow opening a new menu breaks the UI for me.

**Comment by JaggB** [comment]
Personally I also find the new UI horrible, as someone that constantly using about 6 different containers for multiple admin accounts via saved via cookies, it now takes forever opening new containers (ie way too many clicks). For myself, I like the simplicity of the old UI, all I want to do open a new container/tab without doing anything fancy. I'm also finding the font size slightly smaller.

**Comment by groovecoder** [comment]
Thanks everyone for feedback and understanding as we make bug-fixes to our first major UI release in about 2 years. :)

I've merged #1798 to fix keyboard arrow navigation in the panels. (Thanks @kendallcorner !!)

@maxxcrawford and I are also going to work on reverting the first panel main click behavior back to "Open a new tab in this container" by default, and make clicking the right chevron the click that will open the "manage this container" panel.

**Comment by ZingBlue** [comment]
What is the stance on creating issues/PRs here? Can I open a PR describing changes to the UX which were made and if the changes are good, will the PR be accepted? (I'm kinda new to committing to open source projects, I thought this would be a good start).

**Comment by hackel** [comment]
Note that another way to open a new tab in a specific container that's built-in to Firefox is to just use the File -> New Container Tab menu.  Press <kbd>Alt</kbd> + <kbd>f</kbd>, <kbd>b</kbd>, then you can use your arrow keys to move up/down, or press the first letter of the container you want.  No need to reinvent the wheel when it's already built-in!

**Comment by jtagcat** [comment]
You can no longer undo always-open-in. This fundamentally counteracts the add-on's core functionality, as if you try to open an account in a container other than the one, what it has been marked to always open in, it forces you to use the container. Using temporary containers automatic mode (if no container, then get a container) it makes it impossible to use a site with multiple accounts without resetting add-on data, as far as I know of.

Always open in should be replaced / complicated with something like 'if no container, then open in this container'. Keeping temporary containers in mind, 'if no container, or temporary container, open in this container' (it can be achieved the STG way: user has to give STG the temporary container prefix, but imo temporary containers should be part of multi-account-containers anyways).

**Comment by terrycloth** [comment]
> Note that another way to open a new tab in a specific container that's built-in to Firefox is to just use the File -> New Container Tab menu. Press Alt + f, b, then you can use your arrow keys to move up/down, or press the first letter of the container you want.

Yeah, this is much closer to my ideal workflow for Multi-Account Containers. If you could do this from the extension panel (<kbd>Ctrl</kbd>+<kbd>.</kbd> → [first letter of container name] → <kbd>Enter</kbd>, to open a new tab), then it would be even faster. Not as fast as <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>1</kbd>, but much easier to remember than arbitrarily assigned numbers.

I think it's okay for less frequently used actions, like assigning a site to a domain, or hiding all tabs in a given container, to be put away in submenus requiring an extra click or extra keyboard input... because they're not used as often. But I'm opening and closing tabs all day long, and reorganizing the UI the way version 7.0 does makes that most important action less convenient.

**Comment by terrycloth** [comment]
I will acknowledge one improvement about the redesign: With the old UI, managing the container itself required opening the submenu by clicking the little arrow next to the container name, and that button was a pretty small target for mouse users. With the new design, all the buttons are the same size, and I can appreciate that.

...It's just that the current solution means that _every_ action is hidden away in a submenu, which seems silly to me 😝

**Comment by AdKiller** [comment]
Using built in Windows High Contrast theme, the text on multi account container's menu is not visible.

![image](https://user-images.githubusercontent.com/13304436/87544221-60da2000-c6a6-11ea-863b-c7d44ad2d994.png)

**Comment by groovecoder** [comment]
7.0.1 was just published on AMO, with fixes for keyboard arrow navigation, and reverting the main panel item click to open a new tab. Continuing to look thru the comments on this issue and the other issues to prioritize more clean-ups. 

Based on the overall feedback, the most likely next improvement is keyboard shortcuts (and/or a fuzzy-finder type search instead?)

**Comment by charles-m-knox** [comment]
> 
> 
> 7.0.1 was just published on AMO, with fixes for keyboard arrow navigation, and reverting the main panel item click to open a new tab. Continuing to look thru the comments on this issue and the other issues to prioritize more clean-ups.
> 
> Based on the overall feedback, the most likely next improvement is keyboard shortcuts (and/or a fuzzy-finder type search instead?)

@groovecoder Yes, definitely implementing a fuzzy-finder search box would be the biggest improvement. Thank you for your work on this project!

**Comment by umquat** [comment]
7.0.1 is great, thanks a bunch!

minions_clapping.gif :)

**Comment by hackel** [comment]
As @terrycloth mentioned, the chevron is a very small click target to access the container submenu.  It would be nice not only if this icon was a little bit larger, but provided some kind of visual feedback on hover.

I still feel this behaviour is very counter-intuitive and doesn't follow the rest of Firefox's UI design language, e.g. the bookmarks menu and others that have a right chevron.  In every other case it indicates to the user that the entire menu item is clickable to access the submenu.  I would never have guessed that the chevron had a different function if I hadn't read it here.

One possible solution would be to have a hard separation between the menu item and the chevron "button", similar to to a Bootstrap input group, where only the respective area is highlighted on hover.

Just want to add that in general I'm very happy with the 7.0 changes, great job!

**Comment by brisad** [comment]
I just noticed that the keyboard shortcuts for the [Firefox Profiler](https://profiler.firefox.com/) stopped working. I wasn't able to find the place to remap the keys in the UI by myself, until I found this feedback thread and in particular https://github.com/mozilla/multi-account-containers/issues/1784#issuecomment-657001633. I filed https://github.com/mozilla/multi-account-containers/issues/1814 for the conflict.

Thanks for this great addon!

**Comment by smerrill** [comment]
Thanks very much for the 7.0.1 update, and for this tool. The restoration of the arrow key navigation is great and the new `Ctrl-Shift-${NUM}` shortcuts let me select my most used two tabs (Home and Work) with even fewer keystrokes.

**Comment by MrGoatsy** [comment]
The UI is too cluttered now, please put the available tabs on the top and the rest of the features at the bottom.

**Comment by angela-d** [comment]
The update is much better, but it still seems too noisy!  Is it possible to stuff the new options into a menu carat/button, so they aren't yelling at you everytime you have to open a new tab?

The text change is also still a bit jarring - the size prior to 7.0 seemed much more suit.

**Comment by LewS** [comment]
While I can appreciate where the changes are heading, I use multi account containers to isolate client accounts that are in a multi tenant environment so the url is the same for all. Each time I try to open that URL I now get prompted twice to open in a particular container, which is contrary to what is needed. Is there anyway to revert to the previous behavior?

**Comment by michft-v** [comment]
"Is there anyway to revert to the previous behavior?"

How I removed 7.0 and installed 6.2.5. NB I didn't close Firefox during these steps, you may wish to back-up your firefox settings directory any setup before doing these. These restored my previous containers and UI.
1. Select Add-ons and deselect Auto-Update.
2. Remove version 7.
3. goto https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/versions/
4. Select and install 6.2.5

**Comment by JaggB** [comment]
Thank you! It's much better, I can now open a new tab straight away just like before, really appreciate actioning these feedbacks from users

**Comment by nthomas20** [comment]
Every first attempt to try to open the extension either via a direct click or `ctrl + .` yields an unopened container. I must close it and try again to be successful. Latest FF on Kubuntu 20.04.

![Screenshot_20200716_072942](https://user-images.githubusercontent.com/15067067/87671152-76972600-c736-11ea-8fd3-2cbc509cf8a1.png)

**Comment by jimaldon** [comment]
Can I add a URL matching regex rule for assigning to a container? 

I've enabled "Limit to Designated sites" and for a website, when I try to login to a particular website in that container, I end up in a login loop since that website briefly goes to a another URL (which opens in no container) and then jumps back in my assigned container. Since I can't visit the other URL, I can't add it to my site list for that container

**Comment by maxxcrawford** [comment]
@jimaldon I work on [Facebook Container](https://github.com/mozilla/contain-facebook) and site isolation has a hard time with issue like you're describing. Best bet is to add any sites that need to interact in the same container. 

Example – Using a website and Google Auth: Add both the website and accounts.google.com to the container.

**Comment by jimaldon** [comment]
@maxxcrawford Right, my issue is that I can't seem to add the intermediate site that's used for authorization in the container since you're required to visit a URL to be able to add it to the site list. The intermediate site which a subdomain of the same website redirects instantly to another subdomain - making it impossible for me to manually add it to the MAC site list for my container

**Comment by maxxcrawford** [comment]
@nthomas20 Could you please open an issue about that? Thanks!

**Comment by LewS** [comment]
While I can appreciate where the changes are heading, I use multi account containers to isolate client accounts that are in a multi tenant environment so the url is the same for all. Each time I try to open that URL I now get prompted twice to open in a particular container, which is contrary to what is needed. Is there anyway to revert to the previous behavior?

**Comment by jtagcat** [comment]
Manage container tabs button does not show tab count on containers. This is unneeded hiding of information.

**Comment by amicitas** [comment]
The new update 7.0.1 improves things greatly as most of my usage is simply to want to open a new tab in container.  What I would like to see is a new simplified menu button as an option that includes only the containers and none of the menus (similar to the older one). Then the user could choose which menu (full or simplified) to add to their tab bar.

**Comment by maxxcrawford** [comment]
In case anyone is having issues with the keyboard shortcuts, see [this comment](https://github.com/mozilla/multi-account-containers/issues/1814#issuecomment-660157330) for directions and screenshots on how to revise (or remove) any of them. 

(Thanks to @Eduardo06sp and @brisad for highlighting this)

**Comment by maxxcrawford** [comment]
@noph34r @angela-d @aafrasht @cptX The add-on has been updated to restore this functionality. Clicking on the Container icon or name opens a new tab, while clicking on the arrow opens the submenu. 

@cabello We also fixed the arrow keys navigation. Thanks!

**Comment by aafrasht** [comment]
@maxxcrawford Yep, I noticed.  Awesome! This actually does make my life browsing the internet a lot easier.

**Comment by vtuu** [comment]
That's very nice that now we can reopen tab in certain container menu through keyboard, thanks 👍

Check out #1824 , i got more keyboard UX improvement proposals

**Comment by vtuu** [comment]
And there is still sth wrong with the font/font spacing #1786

**Comment by LewS** [comment]
Hi guys I followed michft-v suggestion on how to revert the plugin, and migrated back to 6.2.5 and disabled updates.
But I'm still getting prompted when I open a link...
![image](https://user-images.githubusercontent.com/10936038/87893128-4e832c00-ca82-11ea-8e8c-4555152692e0.png)
Now I can't access one of my client sites at all using firefox, as it's breaking the saml auth.
Any suggestions?

**Comment by maxxcrawford** [comment]
@LewS We recommend upgrading to the latest version of the add-on. We aren't be able to support technical issues related to previous versions. If the issue exists in the latest version, please file a seperate issue!

**Comment by tomaspapi** [comment]
I think @jimaldon's issue could be solved if we were able to add domains manually without having to visit the site. So clicking Manage Containers, selecting one container and writing down a URL we want to include there. This way we can whitelist domains that are only accesed momentarily as part of a redirection flow which cannot be included in any container otherwise.

**Comment by noph34r** [comment]
@maxxcrawford thank you so much
it's back and even better with shortcut
just a little issue with shortcut #10, i dont know the key (still open #1) 
not really a problem much since i can click the last one anyway

**Comment by Eduardo06sp** [comment]
@noph34r here's a comment I previously made :}

> Found the actual shortcuts in one of the commits:
> **Ctrl + Shift + [1-9, or 0 on number row]**
> 
> To open your first 10 containers, which is configurable in the settings!!!
> 
> **Edit:** I had no clue extension shortcuts were a setting in the browser
> You can edit them too!
> Add-ons manager > Gear Icon > Manage Extension Shortcuts

**Comment by maxxcrawford** [comment]
@tomaspapi I dig that ida. Please file an issue for that!

**Comment by maxxcrawford** [comment]
@Eduardo06sp Great call out. I have [a comment](https://github.com/mozilla/multi-account-containers/issues/1814#issuecomment-660157330) that also includes screenshots. 🙌

**Comment by ahayes** [comment]
I have some sites that were set to open in certain containers. I just ran into a situation where I wanted to stop having a site open in a designated container and go back to opening in default but I don't seem to be able to do it. The checkbox is gone and all I seem to be able to do is to pick another container for it to open in. The new "Always Open The Site in..." menu doesn't include default in the list so I can't seem to undo the assignment.

**Comment by tomaspapi** [comment]
@ahayes Go to go to **Manage Containers > [Select Container] > Manage Site List** and from there you can delete any domain associated to the current container.

Hope this helps!

**Comment by maxxcrawford** [comment]
@ahayes @tomaspapi I documented this process (with screenshots) in a [wiki page](https://github.com/mozilla/multi-account-containers/wiki/How-to-remove-a-%22Awlays-open-in%E2%80%A6%22-site-from-a-Container). Thanks!

**Comment by david67nyc** [comment]
Hi - Love the extension, I just have a question - How do we remove a site from a container after it's been assigned to it? V 7 does not show the tick box anymore. Thank you.

**Comment by Hard-Wired** [comment]
An option to delete all containers and/or an option to reset all containers to a first install state. There are times things don't sync correctly and it would be convenient if there was a way to recover to a reset state.

**Comment by ecotechie** [comment]
It would be great if there was a way to only show tabs from a selected container. this would be great for sorting and separating tasks even further. Like work, school, social media, etc.

**Comment by blackjackshellac** [comment]
Keyboard shortcut to "Always open this site in current container"?

If I open a tab in a specific container with Ctrl+Shift+2 and then open a new site there, I still need to go to the extension menu and select "Always open this site in ..." and then choose the container that I'm already in.

As usual, great work and nice progress on the extension.

**Comment by ahayes** [comment]
Thank you @tomaspapi and @maxxcrawford 
Might it also be possible to add "Default (No container)" or similar to the list presented by "Always open in..."

**Comment by navilg** [comment]
How about having an option to open all the subdomains of a site in one particular container under "Always open this site in " ?

E.g. All the subdomains of mozilla (*.mozilla.org) should always open in one particular container.

**Comment by Laurensdc** [comment]
I expect the currently selected tab to be re-opened in container when I hit the shortcut.
E.g.: Hit ctrl+shift+1 -> Open current tab in container 1.

**Comment by yshui** [comment]
The "Manage This Container" button blocks the last tab in the container.

**Comment by MurzNN** [comment]
At previous version was be easier to remove several containers one-by-one, because after deleting one - I will stay on "Manage containers" page and can do one-click for delete next container, but now after deleting - extension returns me to default page, so I need to enter "Manage containers" page again, and scroll down to needed container.

**Comment by dogancelik** [comment]
I want to do `Ctrl + .` then `R` (reopen this site in) then use the numbers (1-9) to change tab containers.

Currently I have to use arrow keys to go to "Reopen this site in" sub-panel which is more time consuming than pressing `Ctrl+. > R > 1`.

**Comment by groovecoder** [comment]
Just because ordering is mentioned here ... #330 was fixed in #1608 and 7.3.0 release is pushed to AMO waiting for review and publish.

**Comment by frnk01** [comment]
Please order the list alphabetically and add support for search. This is a must.

**Comment by grahamperrin** [comment]
> alphabetically

▶ #1866 please

**Comment by santo998** [comment]
Will you add more colors and icons to the containers?
i.e.: a government icon (building), an education icon (graduated student).
Also red, black and blue colors...
There are people like me, who have lot of containers, and with the limited set of icons and colors, its hard to identify them even if you order them alfabetically.

**Comment by grahamperrin** [comment]
> colors

▶ #391 please

> icons

▶ 2017 issue #843, 2018 issue #1185

**Comment by santo998** [comment]
I already replied on those issues threads.
How can i vote to see the features implemented?

**Comment by TheBaus** [comment]
I'm not sure if its the multi-account containers update or an FF update that removed the entire tab being the color I assigned it. Whereas now its a thin strip on top of the tab and a little hard to see compared to the old FF/multi-account containers. 

Would it be possible to add in a feature/toggle to allow the whole tab to be highlighted as to which container I'm in.

**Comment by alchen** [comment]
Can we finally have a sensible solution to edit domain lists and domains that redirects? There have been a number of PR's popping up in the past, but most are left without getting any attention. Any one of them could have solved a myriad of related issues that are keep getting reported.

https://github.com/mozilla/multi-account-containers/pull/1688
https://github.com/mozilla/multi-account-containers/pull/1627
https://github.com/mozilla/multi-account-containers/pull/1613

**Comment by grahamperrin** [comment]
> How can i vote

Thumbs up.

**Comment by achernyakevich-sc** [comment]
I would propose to pay serious attention to the fact that Proton UI in Firefox can't be turned off anymore. So problem with highlighting of tab by the color of container is in place and it is enough serious. You just can't understand which container tab belongs too until you open the tab.

See #2102.

**Comment by kurahaupo** [comment]
@charles-m-knox

> I use a container for each domain, sometimes <em>multiple for the same domain</em>.

Ok, I would love to be able to do this, so how does one set up multiple containers for a single domain? Does that mean attaching a container to a bookmark, or manually selecting a container before opening the site (more than once), or somehow applying "always open in" rules based on something other than just the domain?

**Comment by grahamperrin** [comment]
> multiple containers for a single domain?

1. refrain from always opening the site in any container
2. https://github.com/mozilla/multi-account-containers/issues/854#issuecomment-751410530

**Comment by kannes** [comment]
The latest version gave me an obnoxious ad for a VPN service instead of showing me the containers when I clicked the icon in the menu bar. I had to ready through some manipulative marketing speak and click a "Done" button to be able to see my containers again.

Later I got another ad for the same VPN service in the containers menu that wanted my attention.

Both these events were very unsettling UX events and hampered my experience in using the extension as intended.

Please do not display ads.

**Comment by grahamperrin** [comment]
> obnoxious

Not so. 

Next time you gain a new release, please take a moment to read the release notes. In this case: 

* https://addons.mozilla.org/addon/multi-account-containers/versions/8.0.2/updateinfo

More broadly: 

* https://addons.mozilla.org/addon/multi-account-containers/versions/

**Comment by kannes** [comment]
How would reading the release notes before updating would have prevented me from the unwanted, repeated (once overlaid to the addons bar, once when opening the addon menu for the first time after updating) and misleading (one of the ads did not mention the option to use a self-hosted proxy) advertisements about Mozilla VPN for 5$/month? I know I sound like an annoying troll but seriously, that's how I felt when I saw the ads. UX wise it made me want to shout at the screen.

**Comment by grahamperrin** [comment]
Honestly, I don't sense obnoxiousness in the UX. 

For existing users, after clicking the toolbar icon, it's either: 

1. ☒ dismiss the notification (pictured below); or 
2. click **Learn more**, which, for me in the UK, refers to 
https://www.mozilla.org/en-US/products/vpn/

![image](https://user-images.githubusercontent.com/192271/143720807-9651ee58-2fb4-49a5-8cd3-a1c9877b6ba2.png)

### Onboarding

For newcomers to the extension: 

![image](https://user-images.githubusercontent.com/192271/143720773-7e7dd03c-1929-458c-a62f-c74b06fa144a.png)

**Comment by kannes** [comment]
I got both of them as an existing user.

Any ad is obnoxious, especially ones that popup in previous quite places and that require you to act to get rid of them ;) My wording is strong because I despise advertisements and these really felt out of place.

**Comment by grahamperrin** [comment]
Confirmed, the update UX: 

![image](https://user-images.githubusercontent.com/192271/143721178-12f0a88c-0c8f-47aa-8b35-184bb12ba29b.png)

* learn more, cancel or update

– and if not cancelled, the update is followed by a toolbar hint that leads to the initial onboarding, which mentions the _own proxy_ option. 

> … Any ad is obnoxious, …

That's an extreme sentiment.

**Comment by kannes** [comment]
That is a different step and while I don't know what is hidden behind the "Learn more" link there, the content is standard extension stuff without any commercial endorsement or advertising.

I meant the two dialogs you showed in https://github.com/mozilla/multi-account-containers/issues/1784#issuecomment-980794342, the "Learn more" link there leads to https://www.mozilla.org/en-US/products/vpn/?several_tracking_parameters which has no mention about one's own self-hosted solution, not even that the VPN software is open-source. It is plain advertising for the commercial Mozilla VPN service, is it not?

**Comment by grahamperrin** [comment]
> … advertising …

Would you prefer there to be no mention of the cost of the service? Or no mention of the integration with Mozilla's extension?

**Comment by grahamperrin** [comment]
https://github.com/mozilla/multi-account-containers/issues/1784#issuecomment-980068141

> The latest version

Is **not** 7.0.x. I'm hiding my comments; @kannes please consider taking your 8.0.x feedback to an appropriate issue. Thanks.

**Comment by dannycolin** [comment]
Closing since 7.0 has long been released now :tada:.
