### ISSUE TITLE
Popup panel is empty/blank, does not appear, when apz.allow_zooming = true

### ISSUE THREAD

**Issue by nkestrel** [mozilla/multi-account-containers#382]
FF52 & FF55
Windows 10 & Ubuntu 16.10

This is a bit obscure but `apz.allow_zooming` breaks the popup panel as seen below.

![Image of empty panel](https://i.imgur.com/1BzGN2c.png)

I have not encountered this problem before with other extension popups.

**Comment by groovecoder** [comment]
Whoa, interesting and nice catch. Labeling as bug to try to reproduce.

**Comment by kjozwiak** [comment]
I've managed to reproduce this on macOS 10.12.4 using fx52.0.2. Once you enable `apz.allow_zooming`, the container drop down completely breaks. I'm pinging someone who works on APZ to find out how wide spread this might be and if we actually enable that pref for any users. If we're automatically turning that pref for certain users, we should fix this in the next sprint.

**Comment by kjozwiak** [comment]
I'm moving this into Stretch... Pinged kats from the gfx team on IRC and he mentioned that `apz.allow_zooming` isn't meant to be turned on the desktop. Turning it on the desktop puts you in the "you're on your own category".

**Comment by krzysbaranski** [comment]
I have the same effect without this setting in Firefox Developer Edition 58.0b15, it not happening in my other profile

**Comment by eladkarako** [comment]
`apz.allow_zooming` issue still happens on FF 58 (release).

<hr/>

btw. it might worth mentioning that <strong>this issue also happens</strong> 
when setting `dom.meta-viewport.enabled`-&gt;`true`.

**Comment by nebulade** [comment]
Just to have the crosslink to the same issue in bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1522131

**Comment by dannycolin** [comment]
Closing since it has been resolved upstream.
